# Generated by Django 5.2.13 on 2026-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_brokeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='connection_status',
            field=models.CharField(choices=[('unconfigured', 'Unconfigured'), ('unverified', 'Unverified'), ('connected', 'Connected'), ('error', 'Error')], default='unconfigured', max_length=20),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='flex_query_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='flex_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
