# Generated by Django 5.2.13 on 2026-08-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_brokeraccount_connection_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardPreference',
        ),
    ]
