# Generated by Django 5.2.13 on 2026-08-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_brokeraccount_connection_status_and_more'),
        ('syncs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='broker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='common.brokeraccount'),
        ),
    ]
