# Generated by Django 5.2.13 on 2026-08-06 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_delete_strategyoption'),
        ('journal', '0016_remove_legacy_journal_workflow'),
        ('trades', '0009_raw_execution_broker_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('scaling', 'Scaling'), ('closed', 'Closed'), ('voided', 'Voided')], default='pending', max_length=16)),
                ('entry_at', models.DateTimeField(blank=True, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('planned_risk_r', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('actual_risk_r', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('result_r', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reentry_reason', models.CharField(blank=True, choices=[('planned_retry', 'Planned retry'), ('new_signal', 'New signal'), ('better_price', 'Better price'), ('noise_stop', 'Noise stop'), ('changed_setup', 'Changed setup'), ('emotional', 'Emotional')], default='', max_length=24)),
                ('what_changed', models.TextField(blank=True, default='')),
                ('was_planned', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('neutral', 'Neutral')], max_length=12)),
                ('setup', models.CharField(max_length=100)),
                ('horizon', models.CharField(choices=[('scalp', 'Scalp'), ('intraday', 'Intraday'), ('swing', 'Swing'), ('position', 'Position')], default='intraday', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('review_pending', 'Review Pending'), ('reviewed', 'Reviewed'), ('cancelled', 'Cancelled')], default='planned', max_length=24)),
                ('max_risk_r', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('planned_risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('result_r', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('realized_pnl', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('premarket', 'Premarket'), ('opening', 'Opening'), ('morning', 'Morning'), ('midday', 'Midday'), ('power_hour', 'Power Hour'), ('custom', 'Custom')], default='custom', max_length=24)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed'), ('reviewed', 'Reviewed')], default='planned', max_length=20)),
                ('risk_limit_r', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('result_r', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_environment', models.CharField(blank=True, default='', max_length=120)),
                ('allowed_setups', models.JSONField(blank=True, default=list)),
                ('no_trade_conditions', models.TextField(blank=True, default='')),
                ('stop_rule', models.TextField(blank=True, default='')),
                ('energy_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('focus_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress_score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptFill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_links', to='journal.attempt')),
                ('fill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journal_attempt_link', to='trades.tradefill')),
            ],
            options={
                'ordering': ['fill__executed_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='journal.campaign'),
        ),
        migrations.CreateModel(
            name='DecisionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_evidence', models.JSONField(default=list)),
                ('interpretation', models.TextField()),
                ('strongest_counter_case', models.TextField()),
                ('chosen_action', models.TextField(blank=True, default='')),
                ('entry_trigger', models.TextField()),
                ('invalidation', models.TextField()),
                ('time_stop', models.CharField(blank=True, default='', max_length=160)),
                ('immutable_snapshot_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('revision_no', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_snapshot', to='journal.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confirmation', models.TextField()),
                ('contradiction', models.TextField()),
                ('planned_action', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='journal.decisionsnapshot')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exit_reason', models.CharField(choices=[('target', 'Target'), ('trailing_stop', 'Trailing stop'), ('initial_stop', 'Initial stop'), ('thesis_invalidated', 'Thesis invalidated'), ('time_stop', 'Time stop'), ('market_change', 'Market change'), ('manual_risk', 'Manual risk'), ('emotional', 'Emotional'), ('error', 'Error')], max_length=32)),
                ('entry_followed', models.CharField(choices=[('yes', 'Yes'), ('partly', 'Partly'), ('no', 'No')], max_length=8)),
                ('management_followed', models.CharField(choices=[('yes', 'Yes'), ('partly', 'Partly'), ('no', 'No')], max_length=8)),
                ('exit_followed', models.CharField(choices=[('yes', 'Yes'), ('partly', 'Partly'), ('no', 'No')], max_length=8)),
                ('decision_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('execution_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('outcome_drivers', models.JSONField(default=list)),
                ('hindsight_known_then', models.TextField()),
                ('hindsight_luck', models.TextField()),
                ('hindsight_process', models.TextField()),
                ('would_repeat', models.BooleanField()),
                ('lesson', models.TextField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='journal.campaign')),
                ('actual_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='journal.scenario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='journal.session'),
        ),
        migrations.CreateModel(
            name='SessionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preventable_loss_r', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('normal_variance_r', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('overtrading_flag', models.BooleanField(default=False)),
                ('best_decision', models.TextField(blank=True, default='')),
                ('main_mistake', models.TextField(blank=True, default='')),
                ('next_rule', models.TextField(blank=True, default='')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='journal.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('review_pending', 'Review Pending'), ('reviewed', 'Reviewed'), ('locked', 'Locked')], default='draft', max_length=24)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('daily_risk_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_trades', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('realized_pnl', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_r', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_environment', models.CharField(blank=True, default='', max_length=120)),
                ('closing_note', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_trading_days', to='common.brokeraccount')),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='trading_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='journal.tradingday'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=40)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_audit_events', to='common.brokeraccount')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='journal_aud_aggrega_1ea69f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('campaign', 'sequence_no'), name='journal_unique_attempt_sequence'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['symbol', 'status'], name='journal_cam_symbol_a08682_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradingday',
            constraint=models.UniqueConstraint(fields=('account', 'trade_date'), name='journal_unique_trading_day'),
        ),
    ]
